sudo:
  false

language:
  php

php:
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - if [[ "5.6" == "${TRAVIS_PHP_VERSION}" ]]; then composer phpcs; fi
  - if [[ "5.6" == "${TRAVIS_PHP_VERSION}" ]]; then composer phpmd; fi
  - composer phpunit

notifications:
  email: false
